### PR TITLE
Fix possible data loss after goaway received

### LINKED ISSUE #55: Pending frames in worker queues may not be delivered after goaway frame received
If there are pending frames in the various worker queues and one of the workers processes a goaway frame, it's possible that some of the pending frames may be processed after the streams have been closed down. If you turn on debugging, you'll see 1 or more "Data frame gone away" messages after the connection's Serve() method gets the EOF from the framer trying to read frames.

A solution is to wait for all workers to drain their queues when receiving the goaway frame, and then tear down the streams.

### PR DESCRIPTION
**Pull request by ncdc**
All frames are processed by workers running in goroutines. If 1 worker's
queue is backed up with data frames and another worker receives and
processes a goaway frame, it's a race as to whether or not the workers
will be able to process the pending data frames before the streams are
removed from the streams map.

This fix processes the goaway frame synchronously in Serve() instead of
in a worker goroutine. We now wait for all the workers to drain their
frame queues before tearing down the streams.

Fixes #55

### CODE REVIEW

**Comment by ncdc** [comment]
@liggitt @smarterclayton FYI

**Comment by smarterclayton** [comment]
Test case that demonstrates? :)

**Comment by liggitt** [comment]
we couldn't think of a deterministic one, but one that flooded streams with frames, then sent a goaway consistently dropped the last few frames

**Comment by liggitt** [comment]
could write a mini-soak test to demonstrate

**Comment by smarterclayton** [comment]
I just wanted to have some way of knowing it failed before but not after.

File: connection.go [hunk 1]
```diff
@@ -317,9 +328,9 @@ func (s *Connection) Serve(newHandler StreamHandler) {
 			partition = partitionRoundRobin
 			partitionRoundRobin = (partitionRoundRobin + 1) % FRAME_WORKERS
 		case *spdy.GoAwayFrame:
-			priority = 0
-			partition = partitionRoundRobin
-			partitionRoundRobin = (partitionRoundRobin + 1) % FRAME_WORKERS
+			// handle to go-away frame synchronously here, then exit the loop
+			s.handleGoAwayFrame(frame)
```
Comment (smarterclayton) [inline connection.go]: Who handled this before?  The frame queues?

Comment (liggitt) [inline connection.go]: Yeah, it got put in a queue, so it was possible for other frames to be enqueued after a goaway

**Comment by ncdc** [comment]
I'm working on a test case. So far I haven't had any luck, which is why I
sent out the pr for initial review.

**Comment by smarterclayton** [comment]
The code looks correct to me.  I'm not an expert on the deeper semantics of the frame handling though.

**Comment by dmcgowan** [comment]
I am not convinced `s.handleGoAwayFrame(frame)` should be handled before the wg.Wait() completes and we can be certain all prior frames have been handled. Maybe we store the frame, break the loop, close, wait, then handle? WDYT?

**Comment by ncdc** [comment]
Good point. I had considered that but wasn't sure. I'll update it to do
what you suggested.

**Comment by ncdc** [comment]
Coming back around to this today. I still haven't built a reliable reproducer without forcibly injecting some delays into the main code, but I was able to do so with that approach. I modified the frame handler so that it sleeps 1 second before processing any data frame. In the test case, have a client send multiple data frames over 1 single stream to the server. Have the server verify it receives everything the client sends. Without this fix, you'll see multiple "Data frame gone away for 1" messages as the server tries to process pending data frames after it's already processed the go away frame. With the fix, all frames are delivered, and the test passes. So the only way I can think of right now to reliably test this would be to add some code that evaluates an internal `bool` set by the test code that forces delayed delivery of data frames. I'm not sure that's a good idea, but it's the best thing I have so far...

@dmcgowan how do you want to proceed?

**Comment by ncdc** [comment]
Failure output:
```
$ DEBUG=1 go test -run GoAway
Creating stream
2015/10/16 16:01:18 (0xc8200ce000) (0xc820102000) Create stream
2015/10/16 16:01:18 (0xc8200ce000) (0xc820102000) Stream added, broadcasting: 1
2015/10/16 16:01:18 (0xc8200ba500) Add stream frame: 1
2015/10/16 16:01:18 (0xc8200ba500) (0xc82029a0a0) Stream added, broadcasting: 1
2015/10/16 16:01:18 (0xc82029a0a0) (1) Writing data frame
2015/10/16 16:01:18 (0xc8200ce000) Reply frame received for 1
2015/10/16 16:01:18 (0xc820102000) (1) Writing data frame
2015/10/16 16:01:18 (0xc820102000) (1) Writing data frame
2015/10/16 16:01:18 (0xc820102000) (1) Writing data frame
2015/10/16 16:01:18 (0xc820102000) (1) Writing data frame
2015/10/16 16:01:18 Streams opened: 1, map[spdy.StreamId]*spdystream.Stream{0x1:(*spdystream.Stream)(0xc820102000)}
2015/10/16 16:01:18 (0xc8200ba500) Go away received
2015/10/16 16:01:18 Streams opened: 1, map[spdy.StreamId]*spdystream.Stream{0x1:(*spdystream.Stream)(0xc82029a0a0)}
2015/10/16 16:01:18 (0xc8200ce000) Go away received
2015/10/16 16:01:19 (0xc8200ba500) Data frame received for 1
2015/10/16 16:01:19 (0xc82029a0a0) (1) Data frame handling
2015/10/16 16:01:19 (0xc8200ce000) Data frame received for 1
2015/10/16 16:01:19 (0xc82029a0a0) (1) Data frame sent
2015/10/16 16:01:19 (0xc820102000) (1) Data frame handling
2015/10/16 16:01:19 Stream removed, broadcasting: 1
2015/10/16 16:01:19 EOF received
--- FAIL: TestGoAwayRace (1.01s)
	spdy_test.go:922: Expected "hello1hello2hello3", got "hello1"
```

Success output (note the time difference in between when go away / EOF and when the data frames are delivered):
```
$ DEBUG=1 go test -run GoAway
Creating stream
2015/10/16 16:01:38 (0xc8200ce000) (0xc820100000) Create stream
2015/10/16 16:01:38 (0xc8200ce000) (0xc820100000) Stream added, broadcasting: 1
2015/10/16 16:01:38 (0xc8200ba5a0) Add stream frame: 1
2015/10/16 16:01:38 (0xc8200ba5a0) (0xc82029a0a0) Stream added, broadcasting: 1
2015/10/16 16:01:38 (0xc82029a0a0) (1) Writing data frame
2015/10/16 16:01:38 (0xc8200ce000) Reply frame received for 1
2015/10/16 16:01:38 (0xc820100000) (1) Writing data frame
2015/10/16 16:01:38 (0xc820100000) (1) Writing data frame
2015/10/16 16:01:38 (0xc820100000) (1) Writing data frame
2015/10/16 16:01:38 (0xc820100000) (1) Writing data frame
2015/10/16 16:01:38 (0xc8200ce000) Go away received
2015/10/16 16:01:38 Streams opened: 1, map[spdy.StreamId]*spdystream.Stream{0x1:(*spdystream.Stream)(0xc820100000)}
2015/10/16 16:01:38 Streams opened: 1, map[spdy.StreamId]*spdystream.Stream{0x1:(*spdystream.Stream)(0xc82029a0a0)}
2015/10/16 16:01:39 (0xc8200ce000) Data frame received for 1
2015/10/16 16:01:39 (0xc8200ba5a0) Data frame received for 1
2015/10/16 16:01:39 (0xc82029a0a0) (1) Data frame handling
2015/10/16 16:01:39 (0xc82029a0a0) (1) Data frame sent
2015/10/16 16:01:39 (0xc820100000) (1) Data frame handling
2015/10/16 16:01:39 Stream removed, broadcasting: 1
2015/10/16 16:01:39 EOF received
2015/10/16 16:01:39 (0xc8200ce000) Go away received
2015/10/16 16:01:40 (0xc8200ba5a0) Data frame received for 1
2015/10/16 16:01:40 (0xc82029a0a0) (1) Data frame handling
2015/10/16 16:01:40 (0xc82029a0a0) (1) Data frame sent
2015/10/16 16:01:41 (0xc8200ba5a0) Data frame received for 1
2015/10/16 16:01:41 (0xc82029a0a0) (1) Data frame handling
2015/10/16 16:01:41 (0xc82029a0a0) (1) Data frame sent
2015/10/16 16:01:42 (0xc8200ba5a0) Data frame received for 1
2015/10/16 16:01:42 (0xc82029a0a0) (1) Data frame handling
2015/10/16 16:01:42 Stream removed, broadcasting: 1
PASS
```

**Comment by ncdc** [comment]
Here's the test:

```go
func TestGoAwayRace(t *testing.T) {
  var done sync.WaitGroup
  testFunc := func() {
    listener, err := net.Listen("tcp", "localhost:0")
    if err != nil {
      t.Fatalf("Error listening: %v", err)
    }
    listen := listener.Addr().String()

    serverConnChan := make(chan *Connection)
    done.Add(1)
    go func() {
      defer done.Done()
      serverConn, err := listener.Accept()
      if err != nil {
        t.Fatalf("Error accepting: %v", err)
      }

      serverSpdyConn, err := NewConnection(serverConn, true)
      if err != nil {
        t.Fatalf("Error creating server connection: %v", err)
      }
      serverConnChan <- serverSpdyConn

      streamCh := make(chan *Stream)
      go serverSpdyConn.Serve(func(s *Stream) {
        s.SendReply(http.Header{}, false)
        streamCh <- s
      })

      stream, ok := <-streamCh
      if !ok {
        t.Fatalf("didn't get a stream")
      }
      stream.Close()
      data, err := ioutil.ReadAll(stream)
      if err != nil {
        t.Error(err)
      }
      if e, a := "hello1hello2hello3", string(data); e != a {
        t.Errorf("Expected %q, got %q", e, a)
      }
    }()

    dialConn, err := net.Dial("tcp", listen)
    if err != nil {
      t.Fatalf("Error dialing server: %s", err)
    }
    conn, err := NewConnection(dialConn, false)
    if err != nil {
      t.Fatalf("Error creating client connectin: %v", err)
    }
    defer conn.Close()
    go conn.Serve(NoOpStreamHandler)

    serverConn := <-serverConnChan
    defer serverConn.Close()

    fmt.Println("Creating stream")
    stream, err := conn.CreateStream(http.Header{}, nil, false)
    if err != nil {
      t.Fatalf("error creating client stream: %s", err)
    }
    defer stream.Close()
    if err := stream.Wait(); err != nil {
      t.Fatalf("error waiting for stream creation: %v", err)
    }

    fmt.Fprint(stream, "hello1")
    fmt.Fprint(stream, "hello2")
    fmt.Fprint(stream, "hello3")
  }

  testFunc()
  done.Wait()
}

**Comment by dmcgowan** [comment]
I am not opposed to injecting such code in order to help testing, as long as it does not have an effect on benchmarks or in a critical performance path. We can also make some function override-able by the unit tests by setting some to a var. I have seen this pattern show up more and I have personally found it an effective way to unit test in Go.

**Comment by ncdc** [comment]
I've added a commit which adds a test case where the Connection's data frame handler is now overridable. If you undo the changes to connection.go but keep the test case, you should see it fail.

**Comment by dmcgowan** [comment]
I was able to test it by backing out the first two commits in this PR to prove to myself it does what it claims. The change itself looks really good as well, this is a much better way of handling goaway.

LGTM
